'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { startPaperSession, stopPaperSession, tickPaperSession } from '@/features/paper-trading/services/paperEngine'
import { monitorSession } from '@/features/paper-trading/services/aiMonitor'
import { getLivePrice } from '@/features/paper-trading/services/priceService'
import type { PaperSession, PaperTrade, PaperDashboardData } from '@/features/paper-trading/types'
import type { MonitorReport } from '@/features/paper-trading/services/aiMonitor'

export async function startSession(input: {
  strategyId: string
  symbol: string
  timeframe: string
  initialCapital?: number
}): Promise<PaperSession> {
  return startPaperSession(input)
}

export async function stopSession(sessionId: string): Promise<void> {
  return stopPaperSession(sessionId)
}

export async function tickSession(sessionId: string) {
  return tickPaperSession(sessionId)
}

export async function monitorPaperSession(sessionId: string): Promise<MonitorReport> {
  return monitorSession(sessionId)
}

export async function getPaperSessions(): Promise<PaperSession[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data, error } = await supabase
    .from('paper_sessions')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (error) throw new Error(`Failed to fetch sessions: ${error.message}`)
  return (data ?? []) as PaperSession[]
}

export async function getPaperDashboard(sessionId: string): Promise<PaperDashboardData> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: session } = await supabase
    .from('paper_sessions')
    .select('*')
    .eq('id', sessionId)
    .eq('user_id', user.id)
    .single()

  if (!session) throw new Error('Session not found')

  const { data: trades } = await supabase
    .from('paper_trades')
    .select('*')
    .eq('session_id', sessionId)
    .order('created_at', { ascending: true })

  const allTrades = (trades ?? []) as PaperTrade[]
  const openTrades = allTrades.filter(t => t.status === 'open')
  const closedTrades = allTrades.filter(t => t.status === 'closed')

  let currentPrice = null
  try {
    currentPrice = await getLivePrice(session.symbol)
  } catch {
    // Price fetch is non-blocking
  }

  // Build P&L history from closed trades
  let equity = Number(session.initial_capital)
  const pnlHistory = closedTrades.map(t => {
    equity += Number(t.pnl)
    return { timestamp: t.exit_time ?? t.created_at, pnl: equity - Number(session.initial_capital) }
  })

  return {
    session: session as PaperSession,
    openTrades,
    closedTrades,
    currentPrice,
    pnlHistory,
  }
}

export async function getRecentTrades(limit = 8): Promise<PaperTrade[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data } = await supabase
    .from('paper_trades')
    .select('*, paper_sessions!inner(user_id, symbol)')
    .eq('paper_sessions.user_id', user.id)
    .eq('status', 'closed')
    .order('exit_time', { ascending: false })
    .limit(limit)

  return (data ?? []) as PaperTrade[]
}

// ─── Proposals: scale-up proposals generated by the agentic evaluator ─────────

export async function getPaperProposals(): Promise<{
  id: string
  session_id: string
  proposal_type: string
  proposed_value: Record<string, unknown>
  reason: string
  status: string
  created_at: string
}[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data } = await supabase
    .from('paper_session_proposals')
    .select('*')
    .eq('user_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false })

  return (data ?? []) as {
    id: string; session_id: string; proposal_type: string
    proposed_value: Record<string, unknown>; reason: string; status: string; created_at: string
  }[]
}

export async function respondToProposal(
  proposalId: string,
  response: 'approved' | 'rejected'
): Promise<void> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  // Fetch proposal before updating status (to apply capital change if approved)
  const { data: proposal } = await supabase
    .from('paper_session_proposals')
    .select('proposal_type, proposed_value, session_id')
    .eq('id', proposalId)
    .eq('user_id', user.id)
    .single()

  await supabase
    .from('paper_session_proposals')
    .update({ status: response, responded_at: new Date().toISOString() })
    .eq('id', proposalId)
    .eq('user_id', user.id)

  // If approved and scale_up — apply the capital change to the session
  if (response === 'approved' && proposal?.proposal_type === 'scale_up') {
    const v = proposal.proposed_value as { proposed_capital?: number }
    if (v?.proposed_capital) {
      await supabase
        .from('paper_sessions')
        .update({ current_capital: v.proposed_capital })
        .eq('id', proposal.session_id)
        .eq('user_id', user.id)
    }
  }
}

// ─── Signal Attribution: which signal systems are winning/losing ──────────────

export async function getSignalAttribution(sessionId: string, limit = 15): Promise<{
  system: string
  wins: number
  losses: number
  winRate: number
  contribution: string
}[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: trades } = await supabase
    .from('paper_trades')
    .select('pnl, metadata, exit_reason')
    .eq('session_id', sessionId)
    .eq('status', 'closed')
    .not('exit_reason', 'eq', 'auto_retired')
    .not('exit_reason', 'eq', 'session_stopped')
    .order('exit_time', { ascending: false })
    .limit(limit)

  if (!trades || trades.length === 0) return []

  const systemStats: Record<string, { wins: number; losses: number }> = {}

  for (const trade of trades) {
    const systems: string[] = (trade.metadata as { active_systems?: string[] } | null)?.active_systems ?? []
    const isWin = Number(trade.pnl) > 0

    for (const sys of systems) {
      if (!systemStats[sys]) systemStats[sys] = { wins: 0, losses: 0 }
      if (isWin) systemStats[sys].wins++
      else systemStats[sys].losses++
    }
  }

  return Object.entries(systemStats)
    .map(([system, stats]) => {
      const total = stats.wins + stats.losses
      const winRate = total > 0 ? stats.wins / total : 0
      const contribution = winRate >= 0.65 ? '+++' : winRate >= 0.5 ? '++' : winRate >= 0.4 ? '=' : '-'
      return { system, wins: stats.wins, losses: stats.losses, winRate, contribution }
    })
    .sort((a, b) => b.winRate - a.winRate)
}

export async function getAgentLog(limit = 20): Promise<{
  id: string
  session_id: string
  symbol: string
  timeframe: string
  event_type: string
  reason: string | null
  price: number | null
  pnl: number | null
  created_at: string
}[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  // Get session IDs for this user
  const { data: userSessions } = await supabase
    .from('paper_sessions')
    .select('id')
    .eq('user_id', user.id)

  if (!userSessions || userSessions.length === 0) return []

  const sessionIds = userSessions.map(s => s.id)

  const { data } = await supabase
    .from('paper_agent_log')
    .select('*')
    .in('session_id', sessionIds)
    .order('created_at', { ascending: false })
    .limit(limit)

  return (data ?? []) as {
    id: string; session_id: string; symbol: string; timeframe: string
    event_type: string; reason: string | null; price: number | null; pnl: number | null; created_at: string
  }[]
}

export async function getStrategiesForPaper(): Promise<{ id: string; name: string; symbol?: string }[]> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data } = await supabase
    .from('strategies')
    .select('id, name')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  return (data ?? []) as { id: string; name: string }[]
}
